### ISSUE TITLE
library without implementing FireBase

### ISSUE THREAD

**Issue by pishguy** [facundomedica/fast_qr_reader_view#51]
in our country google firebase is blocked and how can i use this library without implementing that?

```
E/AndroidRuntime(17571): Process: barcodescanner.pishguy.barcode_scanner, PID: 17571
E/AndroidRuntime(17571): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=513469796, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {barcodescanner.pishguy.barcode_scanner/barcodescanner.pishguy.barcode_scanner.MainActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process barcodescanner.pishguy.barcode_scanner. Make sure to call FirebaseApp.initializeApp(Context) first.
E/AndroidRuntime(17571): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5035)
E/AndroidRuntime(17571): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5078)
E/AndroidRuntime(17571): 	at android.app.ActivityThread.-wrap20(Unknown Source:0)
E/AndroidRuntime(17571): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
E/AndroidRuntime(17571): 	at android.os.Handler.dispatchMessage(Handler.java:108)
E/AndroidRuntime(17571): 	at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime(17571): 	at android.app.ActivityThread.main(ActivityThread.java:7523)
E/AndroidRuntime(17571): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17571): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/AndroidRuntime(17571): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
E/AndroidRuntime(17571): Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process barcodescanner.pishguy.barcode_scanner. Make sure to call FirebaseApp.initializeApp(Context) first.
E/AndroidRuntime(17571): 	at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@16.0.2:240)
E/AndroidRuntime(17571): 	at com.google.firebase.ml.vision.FirebaseVision.getInstance(Unknown Source:1)
E/AndroidRuntime(17571): 	at co.apperto.fastqrreaderview.java.barcodescanning.BarcodeScanningProcessor.<init>(BarcodeScanningProcessor.java:55)
E/AndroidRuntime(17571): 	at co.apperto.fastqrreaderview.FastQrReaderViewPlugin$QrReader.open(FastQrReaderViewPlugin.java:570)
E/AndroidRuntime(17571): 	at co.apperto.fastqrreaderview.FastQrReaderViewPlugin$QrReader.access$1400(FastQrReaderViewPlugin.java:342)
E/AndroidRuntime(17571): 	at co.apperto.fastqrreaderview.FastQrReaderViewPlugin$QrReader$1.run(FastQrReaderViewPlugin.java:471)
E/AndroidRuntime(17571): 	at co.apperto.fastqrreaderview.FastQrReaderViewPlugin$CameraRequestPermissionsListener.onRequestPermissionsResult(FastQrReaderViewPlugin.java:255)
E/AndroidRuntime(17571): 	at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:194)
E/AndroidRuntime(17571): 	at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:127)
E/AndroidRuntime(17571): 	at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:137)
E/AndroidRuntime(17571): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7854)
E/AndroidRuntime(17571): 	at android.app.Activity.dispatchActivityResult(Activity.java:7705)
E/AndroidRuntime(17571): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5031)
E/AndroidRuntime(17571): 	... 9 more
I/Process (17571): Sending signal. PID: 17571 SIG: 9
Lost connection to device.

```

**Comment by ekil1100** [comment]
Same situation here, is it possible to use [zxing](https://github.com/zxing/zxing) for Android side? 

I am not a Android developer, but I will try to implement it.

**Comment by facundomedica** [comment]
You've got it, just uploaded a fix using ML Kit 😄
